spring:
  profiles:
    active: development

pricing:
  strategies: Free, One-Time, Subscription

---

server:
  port: 18080
  error:
    whitelabel:
      enabled: false

spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  profiles: development
  datasource:
    url: jdbc:h2:mem:learningdb
    username: learning
    password: learning
    hikari:
      maximum-pool-size: 10
      connection-timeout: 20000
      driver-class-name: org.h2.Driver
      minimum-idle: 10
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
      connection-test-query: SELECT 1
    driver-class-name: org.h2.Driver
logging:
  level:
    org.springframework.web: ERROR
    com.learning: DEBUG
  file:
    name: C:\logs\service.log


---

spring:
  profiles: production
server:
  port: 19090
debug: false